version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: server:${SERVER_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      SERVER_HOST: 0.0.0.0
